lista_terminos_presentes_en_nombres = {'Marca temporal':'marca_temporal',
                                       'Dirección de correo':'email',
                                       'Nombre y apellido':'nombre',
                                       'fecha_entrega':'fecha_entrega',
                                       'Bolsón de verduras verdes':'bolson_verdes',
                                       'Bolsón de pesadas':'bolson_pesadas',
                                       'bolsón de verdes + pesadas + maple':'combo_verdes_pesadas_maple',
                                       'bolsón de verdes + bolsón de pesadas':'combo_verdes_pesadas',
                                       'Peras':'pera',
                                       'Huevos de campo producidos por 3H - Tres Arroyos (Bs As) - Docena - ' : 'docena_huevos',
                                       'Huevos de campo producidos por 3H - Tres Arroyos (Bs As) - Media docena- ' : 'media_docena_huevos',
                                       'Bananas':'banana',
                                       'Paltas':'palta',
                                       'Berenjenas':'berenjena',
                                       'Cebollas':'cebolla',
                                       'Limones':'limon',
                                       'Papa blanca':'papa_blanca',
                                       'Manzana roja':'manzana_roja',
                                       'Zapallo':'zapallo',
                                       'Mandarina':'mandarina',
                                       'Naranja':'naranja',
                                       'Pomelo rosado':'pomelo_rosado',
                                       'Batata morada':'batata_morada',
                                       'Repollo blanco':'repollo_blanco',
                                       'Zapallo anco':'zapallo_anco',
                                       'Zanahoria':'zanahoria',
                                       'Bolsón de frutas':'bolson_frutas',
                                       'Ajo':'ajo',
                                       'Lechuga morada':'lechuga_morada',
                                       'Lechuga francesa':'lechuga_francesa',
                                       'Naranja sanguínea':'naranja_sanguinea',
                                       'Tomate de':'tomate',
                                       'Tomate cherry':'tomate_cherry',
                                       'Manzana verde':'manzana_verde',
                                       'Frutilla':'frutilla',
                                       'Morrón verde':'morron_verde',
                                       '¿Dónde':'casa_popular',
                                       #acá empieza lo que agregué del diccionario_productos
                                       'Yerba mate "Las Tunas" 1kg - ': 'yerba_las_tunas_1kg',
                                       'Yerba mate "Grapia milenaria" 500g - ' : 'yerba_grapia_milenaria_500_g',
                                       'Yerba Mate "Yerbal Viejo" 500g -': 'yerba_yerbal_viejo_500_g',
                                       'Yerba Mate "Orembaé" 1kg - ': 'yerba_orembae_1_kg',
                                       'Yerba Mate "Grapia Milenaria" - 1kg - ':'yerba_grapia_milenaria_1_kg',
                                       'Miel':'miel',
                                       'Tomates perita':'tomate_perita',
                                       'Cebollas moradas': 'cebolla_morada',
                                       'Mandioca':'mandioca',
                                       'Harina de trigo integral' : 'harina_trigo_integral',
                                       'Tapas para empanadas' : 'tapas_empanadas_12',
                                       'Orégano' : 'oregano',
                                       'Zuchini ': 'zuchini',
                                       'Manzanas' : 'manzana',
                                       'Pascualina':'pascualina',
                                       'Polenta':'polenta',
                                       'Detergente' : 'detergente',
                                       'Granola' : 'granola',
                                       'Zapallo kabutia' : 'zapallo_kabutia',
                                       'Chimichurri' : 'chimichurri',
                                       'Jabón líquido' : 'jabon_liquido',
                                       'Tintura' : 'tintura',
                                       'Tomate triturado' : 'tomate_triturado',
                                       'Mermelada de Duraznos' :'mermelada_durazno',
                                       'Jengibre' : 'jengibre',
                                       'Grisines' : 'grisines',
                                       'Aceitunas Verdes' : 'aceituna_verde',
                                       'Azúcar mascabo' : 'azucar_mascabo',
                                       'Arroz integral' : 'arroz_integral',
                                       'Poroto de soja' : 'poroto_soja',
                                       'Poroto alubia': 'poroto_alubia',
                                       'Poroto colorado' : 'poroto_colorado',
                                       'Poroto negro' : 'poroto_negro',
                                       'Mate Cocido' : 'mate_cocido',
                                       'Te negro':'te_negro',
                                       'Queso pategrás' : 'queso_pategras',
                                       'Chorizo colorado' :'chorizo_colorado'




                                       }
lista_de_valores_originales = []
for nombre_clave in lista_terminos_presentes_en_nombres:
  lista_de_valores_originales.append(lista_terminos_presentes_en_nombres[nombre_clave])

diccionario_productos={'🥦🥕 Bolsón de verduras verdes agroecológicas (5 kg aprox.) con variedades de estación - Productorxs de Escobar - ': 'bolson_verdes',
'🥔🧅 Bolsón de pesadas agroecológicas (3kg aprox.) - ' :'bolson_pesadas',
'🥔🥦🥚Agrocombo: bolsón de verdes + pesadas + maple de huevos  '  : 'combo_verdes_pesadas_maple',
'🍐Peras de Neuquén-1 kg - ' : 'pera',
'🥚🥚  Huevos de campo producidos por 3H - Tres Arroyos (Bs As) - Docena - ' : 'docena_huevos',
'🍌Bananas de Jujuy- 1kg - ' : 'banana',
'Yerba mate "Las Tunas" 1kg - ': 'yerba_las_tunas_1kg',
'Miel pura "Monte Adentro" - 500g - ' : 'miel',
'🥚 Huevos de campo producidos por 3H - Tres Arroyos (Bs As) - Media docena- ' : 'media_docena_huevos',
'🍅Tomates perita de Mendoza - 1kg - ' : 'tomate_perita',
'🥑Paltas silvestres de Misiones - 1kg- ': 'palta',
'🍆Berenjenas de Mendoza- 1kg - ': 'berenjena',
'🥕Zanahorias de Mendoza -1kg- ' : 'zanahoria',
'🧅 Cebollas moradas de Mendoza - 1kg - ': 'cebolla_morada',
'🧄 Ajos biodinámicos de Mendoza - por unidad -':'ajo',
'🍋Limones de Tucumán - 1kg - ' : 'limon',
'Mandiocas de Misiones - 1kg- ':'mandioca',
'Harina de trigo integral agroecológica "Naturaleza Viva" 1kg - ' : 'harina_trigo',
'Tapas para empanadas horno 330g por 12U "La Litoraleña" - ' : 'tapas_empanadas_12',
'Orégano agroecológico "Crece desde el pie" 50g - ' : 'oregano',
'Zuchini de Mendoza - 1kg - ': 'zuccini',
'🥔 Papa blanca de Mar del Plata (Bs As) - 1kg - ' : 'papa_blanca',
'Zapallo anco del Delta (Bs As) - 1kg - ' : 'zapallo_anco',
'🍎 Manzanas gala de Neuquén - 1kg - ' : 'manzana',
'Pascualina hojaldre "La Litoraleña" 2U 400 grs - ':'pascualina',
'Polenta "Del Campo" 500g - ':'polenta',
'Detergente lavavajillas "Burbuja Latina" 750ml - ' : 'detergente',
'Granola clásica "Cuyo Natural" 500g - ' : 'granola',
'Zapallo kabutia de Mendoza - 1kg- ' : 'zapallo_kabutia',
'🍊 Mandarinas de San Pedro - 1 kg - ': 'mandarina',
'🟠 Naranjas de San Pedro - 1kg- ' : 'naranja' ,
'Pomelos rosados de Tucumán - 1kg- ' : 'pomelo_rosado',
'Yerba mate "Grapia milenaria" 500g - ' : 'yerba_grapia_milenaria_500_g',
'Chimichurri "Crece desde el pie" 25g - ' : 'chimichurri',
'Jabón líquido para manos Manzana "Burbuja Latina" 950ml - ' : 'jabon_liquido',
'Tintura madre compuesta: Inductora del sueño. Ansiolítica y Relajante "Pájaro Tigre" 60ml - ' : 'tintura_somifera',
'Tomate triturado agroecológico "Sabores del Huanacache" 950gr - ' : 'tomate_triturado',
'Mermelada de Duraznos "Blason" 460g - ' :'mermelada_durazno',
'Jengibre - 100gr - ' : 'jengibre',
'Grisines de salvado "Grissinopoli" 180g - ' : 'grisines',
'Aceitunas Verdes orgánicas "San Nicolás" 500g - ' : 'aceituna_verde',
'Azúcar mascabo agroecológica 500gr - ' : 'azucar_mascabo',
'Arroz integral fino agroecológico "Naturaleza Viva" 1kg - ' : 'arroz_integral',
'Poroto de soja orgánico "Salve la tierra" 500g - ' : 'poroto_soja',
'Poroto alubia orgánico "Salve la Tierra" 500g - ': 'poroto_alubia',
'Poroto colorado orgánico "Salve la Tierra" 500g - ' : 'poroto_colorado',
'Poroto negro orgánico "Salve la Tierra" 500g - ' : 'poroto_negro',
'Mate Cocido Económico "Tucangua" 25 saquitos - ' : 'mate_cocido',
'Te negro económico "Tucangua" 25 saquitos':'te_negro',
'Queso pategrás con orégano -300 grs "Doña Cuchara" - ' : 'queso_pategras',
'Chorizo colorado "Torgelon 58" Unidad 200gr - ' :'chorizo_colorado'}

diccionario_2={
    '🍐Peras de Neuquén - 1 kg - ': 'pera', #ya estaba
'🧅 Cebollas de Mendoza - 1kg - ': 'cebolla', #ya esta
'🧄 Ajos de Mendoza - por unidad - ': 'ajo', #ya esta
'🥔 Papa blanca de Mendoza - 1kg - ':'papa_mendoza',
'Grisines de malteado "Grissinopoli" 180g - ':'grisines', #ya está
'Aceitunas verdes rellenas con morrón "Cuyo Natural" 370gr - ':'aceituna_verde',
'Mate Cocido Económico "Tucanguá" 25 saquitos - ':'mate_cocido', #ya está
'Te negro económico "Tucanguá" 25 saquitos - ':'te_negro', #ya esta
'Zapallito verde de Mendoza - 1kg - ': 'zapallito',
'🥒 Pepino de Mendoza - 1kg - ': 'pepino',
'Batata morada de Misiones - 1kg - ': 'batata',
'Cúrcuma de Misiones - 100gr - ': 'curcuma',
'Quinoto de Tucumán - 1kg - ': 'quinoto',
'🥝 Kiwi de Buenos Aires - 1kg - ': 'kiwi',
'🍍 Ananá de Misiones - por unidad (1,3kg aprox.) - ': 'ananá',
'Yerba Mate "Yerbal Viejo" 500g -': 'yerba_yerbal_viejo_500_g',
'Yerba Mate "Orembaé" 1kg - ': 'yerba_orembae_500_g',
'Queso Tybo Barra feteado "Master Cheese" bandeja 150g - ':'queso_tybo',
'Aceite de oliva extra virgen orgánico "San Nicolas" 500cc - ': 'aceite_oliva',
'Arvejas orgánicas "Salve la Tierra" 500g - ' : 'arvejas',
'Avena arrollada "Salve la Tierra" 500g - ': 'avena',
'Poroto mung orgánico "Salve la Tierra" 500g - ': 'poroto_mug',
'Maní salado "Cuyo Natural" 500g - ': 'mani',
'Lechuga capuchina - por unidad (aprox. 300g) - ': 'lechuga_capuchina',
'Lechuga manteca - por unidad (aprox. 300g) - ': 'lechuga_manteca',
'Repollo blanco - por unidad (aprox. 900g) - ': 'repollo_blanco',
    '🧄 Ajos de Mendoza - por unidad -':'ajo'}

diccionario_3 ={'🍋Limones del Delta (Bs. As.) - 1kg - ': 'limon',
 '🟠 Naranjas del Delta (Bs. As.) - 1kg- ': 'naranja',
 'Pomelo rojo de Tucumán - 1kg- ': 'pomelo',
 'Batata beauregard (boniato) de Misiones - 1kg - ':'batata',
 'Quinoto del Delta (Bs. As.) - 1kg - ': 'quinoto',
 'Lechuga capuchina de Escobar - por unidad (aprox. 300g) - ':'lechuga_capuchina',
 'Lechuga manteca de Escobar - por unidad (aprox. 300g) - ': 'lechuga_manteca',
 '🍅 Tomate de Jujuy - 1kg - ':'tomate',
 ' Morrón verde de Mendoza - 1kg - ': 'morron_verde',
 'Papines de Iruya (Salta) - 500g - ': 'papines',
 'Zapallo anco del Delta (Bs. As.) - 1kg - ': 'zapallo_anco',
 'Aceite de girasol "Zanoni" 1,5L - ':'aceite_girasol'}

diccionario_4={
  '🥔🥦🥚 Agrocombo: bolsón de verdes + pesadas + maple de huevos  ':'combo_verdes_pesadas_maple',
 '🥔🥦 Combo bolsón de verdes + bolsón de pesadas - ':'combo_verdes_pesadas',
 '🧅 Cebollas de Coop. Lejardinere - 1kg - ': 'cebolla',
 '🧄 Ajos de Mendoza - por unidad -':'ajo',
 'Zapallo kabutia de Coop. Lejardinere - 1kg- ':'zapallo_kabutia',
 '🟠 ¡PROMO! Naranjas del Delta (Bs. As.) - 1kg- ': 'naranja',
 'Mate cocido económico "Tucanguá" 25 saquitos - ': 'mate_cocido',
 'Queso pategrás natural -300 grs "Doña Cuchara" - ': 'queso_pategras',
 'Batata Arapey - 1kg - ':'batata',
 '🥝 ¡PROMO! Kiwi de Buenos Aires - 1kg - ': 'kiwi',
 'Yerba Mate "Yerbal Viejo" 500g - ': 'yerba_yerbal_viejo_500_g',
 'Aceite de oliva "Zampal" extra virgen 500cc  - ': 'aceite_oliva',
 'Zapallo anco de Mendoza - 1kg - ': 'zapallo_anco',
 'Aceite de girasol puro "El Cortijo" 900ml  - ': 'aceite_girasol',
 '🥕 Zanahoria del Colectivo Agro - 1kg - ': 'zanahoria',
 'Aceitunas Verdes "Zampal" 500g - ': 'aceituna_verde'
}

diccionario_5={'🥑Paltas silvestres de Misiones - 1kg - ':'palta',
 'Zapallo kabutia de Coop. Lejardinere - 1kg - ': 'zapallo_kabutia',
 '🍊 Mandarina de Entre Ríos - 1 kg - ': 'mandarina',
 '🟠 Naranja de Entre Ríos - 1kg- ':'naranja',
 'Batata morada - 1kg - ': 'batata_morada',
 'Yerba Mate "Grapia Milenaria" 500g - ': 'yerba_grapia_milenaria_500_g',
 'Yerba Mate "Grapia Milenaria" - 1kg - ':'yerba_grapia_milenaria_1_kg',
 'Lechuga morada de Escobar - por unidad (aprox. 300g) - ': 'lechuga_morada',
 '🥕 Zanahoria de Mendoza - 1kg - ': 'zanahoria',
 '🍊 🍎 Bolsón de frutas 3kg (1kg naranja, 1kg mandarina, 0,5kgs manzana, 0,5kgs pera) - ': 'bolson_frutas',
 'Cebolla morada de Mendoza - 1kg - ': 'cebolla_morada',
 '🧄 Ajo de Mendoza - por unidad - ': 'ajo',
 'Jengibre de Misiones - 100g - ': 'jenjibre',
 'Naranja sanguínea de Tucumán - 1kg - ': 'naranja',
 'Polenta "Del Campo" - 500g - ': 'polenta',
 'Poroto adzuki orgánico "Salve la Tierra" - 500lada_durazno, Mermelada de Duraznosg - ': 'poroto_adzuki',
 'Sal del Himalaya (sal rosa) - 200g - ': 'sal_himalaya',
 'Chorizo colorado "Torgelón 58" - 200gr - ':'chorizo_colorado',
 'Romero "Taku" - 25grs - ': 'romero',
 'Laurel en hojas "Taku" - 25grs - ': 'laurel'
}

diccionario_6={'Aceitunas verdes rellenas con parmesano en oliva "Cuyo Natural" 370gr - ': 'aceitunas_rellenas_parmesano',
 'Queso pategrás natural - 300 grs "Doña Cuchara" - ': 'queso_pategras',
 'Yerba Mate "Orembaé" 500g - ': 'yerba_orembae_500_g',
 'Avena arrollada "Salve la Tierra" 1kg - ':'avena',
 ' Morrón verde de Jujuy - 1kg - ': 'morron_verde',
 'Tomate cherry - 1kg - ': 'tomate_cherry',
 '🥦 Brócoli - por unidad - ': 'brocoli',
 'Vino malbec orgánico "Vinecol" 750ml - ': 'vino_malbec',
 'Salsa deshidratada picante carnaval "Naturalito Andino" 60g - ': 'salsa_picante',
 'Salsa deshidratada curry de la Quebrada "Naturalito Andino" 60g - ': 'salsa_curry',
 'Vino merlot roble "Cavas del Artesano" 750ml - ': 'vino_merlot',
 'Queso tybo barra feteado "Master Cheese" bandeja 150g - ': 'queso_tybo'}

diccionario_7={'🥑Paltas silvestres de Tucumán - 1kg - ': 'paltas',
 '🍎 Manzana roja de Río Negro - 1kg - ': 'manzana_roja',
 'Yerba Mate "Yerbal viejo" 500g - ': 'yerba_yerbal_viejo_500_g',
 'Salsa deshidratada verde yunga "Naturalito Andino" 60g - ': 'salsa_verde',
 'Mandioca de Misiones - 1kg - ':'mandioca',
 '🍏 Manzana verde de Neuquén - 1kg - ':'manzana_verde',
 'Polenta "Del campo" - 500g - ': 'polenta',
 'Dulce de leche de cabra "Monte Adentro" - 500gr - ': 'dulce_de_leche',
 'Mix de frutas secas "Crece desde el pie" - 50g - ':'mix_frutas_secas'}

diccionario_8={'🥔🧅 Bolsón de pesadas agroecológicas 3kg (1,5kgs papa, 1kg cebolla, 0,5kgs batata morada) - ': 'bolson_pesados',
 '🍐Peras de Río Negro - 1 kg - ':'peras',
 '🍆Berenjenas de Jujuy - 1kg - ': 'berenjenas',
 '🍋Limones de Entre Ríos - 1kg - ': 'limones',
 'Zapallo kabutia de Mendoza - 1kg - ': 'zapallo_kabutia',
 '🟠 Naranja de Entre Ríos - 1kg - ':'naranja',
 'Pomelo rosado de Entre Ríos - 1kg - ': 'pomelo',
 'Grisines de malteados "Grissinopoli" 180g - ': 'grisines',
 'Queso cremoso orgánico  "El Abascay" - 500g - ': 'queso_cremoso',
 'Lechuga francesa de Escobar - por unidad (aprox. 300g) - ': 'lechuga_francesa',
 'Zapallo anco de Jujuy - 1kg - ': 'zapallo_anco',
 '🧄 Ajo de Mendoza - por 100gr - ': 'ajo',
 'Jengibre de Misiones - 100gr - ': 'jengibre',
 'Tomate cherry de Jujuy - 1kg - ': 'tomate_cherry',
 'Vino cabernet sauvignon orgánico "Vinecol" 750ml - ': 'vino_cabernet',
 'Salsa deshidratada Picante Carnaval "Naturalito Andino" - 60g - ': 'salsa_picante',
 '🍏 Manzana verde de Río Negro - 1kg - ': 'manzana_verde',
 'Mix de Frutas Deshidratadas "Crece desde el pie" - 50g - ': 'mix_frutas_deshidratadas',
 'Ricotta orgánica "El Abascay" - 500g - ':'ricota',
 'Manteca orgánica "El Abascay" - 140g - ': 'manteca',
 'Tomate triturado agroecológico "Manos del Pueblo" - 950cc - ': 'tomate_triturado'}

diccionario_9={'🍎 Manzana roja de Neuquén - 1kg - ':'manzana',
 'Pomelo rojo de Entre Ríos - 1kg - ': 'pomelo',
 'Repollo blanco de Escobar - por unidad (aprox. 900g) - ': 'repollo',
 'Mix de frutas deshidratadas "Crece desde el pie" - 50g - ': 'mix_frutas_deshidratadas',
 'Jabón de coco 100% natural - 150gr - ':'jabon_coco',
 '🍓 Frutilla de Escobar - 1kg - ': 'frutilla',
 'Morrón verde de Corrientes - 1kg - ': 'morron_verde',
 'Arándanos clampshel de Tucumán - 125gr - ': 'arandanos',
 'Queso crema "Rebelde" sin TACC - 280gr - ': 'queso_crema',
 'Queso gouda orgánico "El Abascay" -  300g - ': 'queso_gouda',
 'Harina de trigo integral agroecológica "Naturaleza Viva" - 1kg - ': 'harina_trigo',
 'Fécula de mandioca - 1kg - ': 'fecula_mandioca',
 'Rebozador natural de mandioca "Oro del Inca" - 500gr - ': 'rebozado_mandioca',
 'Chorizo colorado "Torgelon 58" - por unidad (200gr) - ': 'chorizo_colorado',
 'Miel pura "Monte adentro" - 1kg - ': 'miel',
 'Orégano agroecológico "Crece desde el pie" - 50g - ': 'oregano'}